const { sqliteTable, text, integer, real } = require("drizzle-orm/sqlite-core");

const id = () => text("id").primaryKey();

const users = sqliteTable("users", {
  id: id(),
  name: text("name").notNull(),
  firstName: text("first_name").notNull().default(""),
  middleName: text("middle_name").notNull().default(""),
  lastName: text("last_name").notNull().default(""),
  username: text("username").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull(),
  job: text("job").notNull().default("tecnico"),
  phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""),
  document: text("document").notNull().default(""),
  address: text("address").notNull().default(""),
  city: text("city").notNull().default(""),
  state: text("state").notNull().default(""),
  zip: text("zip").notNull().default(""),
  notes: text("notes").notNull().default(""),
  laborRate: real("labor_rate").notNull().default(0),
  canTech: integer("can_tech").notNull().default(1),
  active: integer("active").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

const customers = sqliteTable("customers", {
  id: id(),
  code: text("code").notNull().default(""),
  name: text("name").notNull(),
  firstName: text("first_name").notNull().default(""),
  middleName: text("middle_name").notNull().default(""),
  lastName: text("last_name").notNull().default(""),
  phone: text("phone").notNull().default(""),
  phonesJson: text("phones_json").notNull().default("[]"),
  email: text("email").notNull().default(""),
  document: text("document").notNull().default(""),
  address: text("address").notNull().default(""),
  city: text("city").notNull().default(""),
  state: text("state").notNull().default(""),
  zip: text("zip").notNull().default(""),
  notes: text("notes").notNull().default(""),
  company: text("company").notNull().default(""),
  type: text("type").notNull().default("particular"),
  status: text("status").notNull().default("activo"),
  source: text("source").notNull().default("mostrador"),
  taxExempt: integer("tax_exempt").notNull().default(0),
  accountOpen: integer("account_open").notNull().default(0),
  creditLimit: real("credit_limit").notNull().default(0),
  discountPct: real("discount_pct").notNull().default(0),
  preferredContact: text("preferred_contact").notNull().default("phone"),
  language: text("language").notNull().default(""),
  birthday: text("birthday").notNull().default(""),
  marketing: integer("marketing").notNull().default(1),
  contactsJson: text("contacts_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull().default(""),
});

const customerNotes = sqliteTable("customer_notes", {
  id: id(),
  customerId: text("customer_id").notNull(),
  body: text("body").notNull(),
  userName: text("user_name").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

const vehicles = sqliteTable("vehicles", {
  id: id(),
  vin: text("vin").notNull(),
  make: text("make").notNull(),
  model: text("model").notNull(),
  year: integer("year").notNull(),
  color: text("color").notNull().default(""),
  plate: text("plate").notNull().default(""),
  km: integer("km").notNull().default(0),
  cost: real("cost").notNull().default(0),
  price: real("price").notNull().default(0),
  status: text("status").notNull().default("en_stock"),
  customerId: text("customer_id"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  stockNumber: text("stock_number").notNull().default(""),
  trim: text("trim").notNull().default(""),
  bodyStyle: text("body_style").notNull().default(""),
  engine: text("engine").notNull().default(""),
  transmission: text("transmission").notNull().default(""),
  drivetrain: text("drivetrain").notNull().default(""),
  fuel: text("fuel").notNull().default(""),
  interiorColor: text("interior_color").notNull().default(""),
  doors: integer("doors").notNull().default(0),
  condition: text("condition").notNull().default("usado"),
  location: text("location").notNull().default(""),
  keyNumber: text("key_number").notNull().default(""),
  unitNumber: text("unit_number").notNull().default(""),
  acquiredAt: text("acquired_at"),
  insurance: text("insurance").notNull().default(""),
  insurancePolicy: text("insurance_policy").notNull().default(""),
  licenseExpiry: text("license_expiry").notNull().default(""),
  inspectionDue: text("inspection_due").notNull().default(""),
  productionDate: text("production_date").notNull().default(""),
  alert: text("alert").notNull().default(""),
  updatedAt: text("updated_at").notNull().default(""),
});

const vehicleNotes = sqliteTable("vehicle_notes", {
  id: id(),
  vehicleId: text("vehicle_id").notNull(),
  body: text("body").notNull(),
  userName: text("user_name").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

const sales = sqliteTable("sales", {
  id: id(),
  customerId: text("customer_id").notNull(),
  vehicleId: text("vehicle_id").notNull(),
  price: real("price").notNull(),
  taxRate: real("tax_rate").notNull().default(0),
  tax: real("tax").notNull().default(0),
  downPayment: real("down_payment").notNull().default(0),
  paymentMethod: text("payment_method").notNull().default("contado"),
  status: text("status").notNull().default("borrador"),
  notes: text("notes").notNull().default(""),
  closedAt: text("closed_at"),
  deliveredAt: text("delivered_at"),
  createdAt: text("created_at").notNull(),
});

const salePayments = sqliteTable("sale_payments", {
  id: id(),
  saleId: text("sale_id").notNull(),
  amount: real("amount").notNull(),
  method: text("method").notNull().default("efectivo"),
  paidAt: text("paid_at").notNull(),
  notes: text("notes").notNull().default(""),
});

const parts = sqliteTable("parts", {
  id: id(),
  sku: text("sku").notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  location: text("location").notNull().default(""),
  stock: integer("stock").notNull().default(0),
  minStock: integer("min_stock").notNull().default(0),
  cost: real("cost").notNull().default(0),
  price: real("price").notNull().default(0),
  createdAt: text("created_at").notNull(),
  oem: text("oem").notNull().default(""),
  altsJson: text("alts_json").notNull().default("[]"),
  brand: text("brand").notNull().default(""),
  category: text("category").notNull().default("otros"),
  vendor: text("vendor").notNull().default(""),
  core: real("core").notNull().default(0),
  taxable: integer("taxable").notNull().default(1),
  uom: text("uom").notNull().default("pza"),
  maxStock: integer("max_stock").notNull().default(0),
  onOrder: integer("on_order").notNull().default(0),
  status: text("status").notNull().default("activo"),
  specialOrder: integer("special_order").notNull().default(0),
  notes: text("notes").notNull().default(""),
  updatedAt: text("updated_at").notNull().default(""),
});

const workOrders = sqliteTable("work_orders", {
  id: id(),
  number: text("number").notNull(),
  customerId: text("customer_id").notNull(),
  vehicleId: text("vehicle_id").notNull(),
  status: text("status").notNull().default("recepcion"),
  kind: text("kind").notNull().default("orden"),
  complaint: text("complaint").notNull().default(""),
  cause: text("cause").notNull().default(""),
  correction: text("correction").notNull().default(""),
  notes: text("notes").notNull().default(""),
  kmIn: integer("km_in").notNull().default(0),
  kmOut: integer("km_out").notNull().default(0),
  promisedAt: text("promised_at"),
  techUserId: text("tech_user_id"),
  taxRate: real("tax_rate").notNull().default(0),
  discountPct: real("discount_pct").notNull().default(0),
  waiter: integer("waiter").notNull().default(0),
  priority: text("priority").notNull().default("normal"),
  poNumber: text("po_number").notNull().default(""),
  authorizedAt: text("authorized_at"),
  authorizedBy: text("authorized_by").notNull().default(""),
  holdReason: text("hold_reason").notNull().default(""),
  createdAt: text("created_at").notNull(),
  deliveredAt: text("delivered_at"),
  updatedAt: text("updated_at").notNull().default(""),
});

const workOrderLines = sqliteTable("work_order_lines", {
  id: id(),
  workOrderId: text("work_order_id").notNull(),
  type: text("type").notNull(),
  description: text("description").notNull(),
  partId: text("part_id"),
  opCodeId: text("op_code_id"),
  qty: real("qty").notNull().default(1),
  unitPrice: real("unit_price").notNull().default(0),
  unitCost: real("unit_cost").notNull().default(0),
  payType: text("pay_type").notNull().default("cliente"),
  authorized: integer("authorized").notNull().default(1),
  complaint: text("complaint").notNull().default(""),
  cause: text("cause").notNull().default(""),
  correction: text("correction").notNull().default(""),
});

const opCodes = sqliteTable("op_codes", {
  id: id(),
  code: text("code").notNull(),
  description: text("description").notNull(),
  category: text("category").notNull().default("mantenimiento"),
  payType: text("pay_type").notNull().default("cliente"),
  laborHours: real("labor_hours").notNull().default(1),
  laborRate: real("labor_rate").notNull().default(0),
  price: real("price").notNull().default(0),
  cost: real("cost").notNull().default(0),
  skillLevel: text("skill_level").notNull().default("B"),
  concern: text("concern").notNull().default(""),
  cause: text("cause").notNull().default(""),
  correction: text("correction").notNull().default(""),
  popular: integer("popular").notNull().default(0),
  active: integer("active").notNull().default(1),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

const opCodeParts = sqliteTable("op_code_parts", {
  id: id(),
  opCodeId: text("op_code_id").notNull(),
  partId: text("part_id").notNull(),
  qty: real("qty").notNull().default(1),
});

const workOrderPayments = sqliteTable("work_order_payments", {
  id: id(),
  workOrderId: text("work_order_id").notNull(),
  amount: real("amount").notNull(),
  method: text("method").notNull().default("efectivo"),
  paidAt: text("paid_at").notNull(),
  notes: text("notes").notNull().default(""),
});

const shopSettings = sqliteTable("shop_settings", {
  id: id(),
  name: text("name").notNull().default("Dealer DMS"),
  phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""),
  address: text("address").notNull().default(""),
  taxLabel: text("tax_label").notNull().default("GST"),
  taxRate: real("tax_rate").notNull().default(5),
  gstNumber: text("gst_number").notNull().default(""),
  woPrefix: text("wo_prefix").notNull().default("OT"),
  woNextNumber: integer("wo_next_number").notNull().default(1),
  woPad: integer("wo_pad").notNull().default(4),
  laborRate: real("labor_rate").notNull().default(145),
  invoiceNotes: text("invoice_notes").notNull().default(""),
  serviceMode: text("service_mode").notNull().default("completo"),
  opcodeCategories: text("opcode_categories").notNull().default(""),
  partCategories: text("part_categories").notNull().default(""),
  partUoms: text("part_uoms").notNull().default(""),
});

const expenses = sqliteTable("expenses", {
  id: id(),
  amount: real("amount").notNull(),
  category: text("category").notNull().default("otros"),
  method: text("method").notNull().default("efectivo"),
  spentAt: text("spent_at").notNull(),
  notes: text("notes").notNull().default(""),
});

const incomes = sqliteTable("incomes", {
  id: id(),
  amount: real("amount").notNull(),
  method: text("method").notNull().default("efectivo"),
  receivedAt: text("received_at").notNull(),
  notes: text("notes").notNull().default(""),
  category: text("category").notNull().default("otros"),
});

const inventoryMovements = sqliteTable("inventory_movements", {
  id: id(),
  partId: text("part_id").notNull(),
  qty: integer("qty").notNull(),
  reason: text("reason").notNull(),
  workOrderLineId: text("work_order_line_id"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

module.exports = {
  users,
  customers,
  customerNotes,
  vehicles,
  vehicleNotes,
  sales,
  salePayments,
  parts,
  workOrders,
  workOrderLines,
  inventoryMovements,
  opCodes,
  opCodeParts,
  workOrderPayments,
  shopSettings,
  expenses,
  incomes,
};
